//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLogin
    {
        public int LoginID { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> RecentLoginTime { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string RandomCode { get; set; }
        public string Email { get; set; }
        public string CreateWay { get; set; }
        public string Alias { get; set; }
        public Nullable<int> MobilePlatform { get; set; }
        public Nullable<int> LoginState { get; set; }
        public string Gmd { get; set; }
        public Nullable<System.DateTime> OverdueTime { get; set; }
        public string NickName { get; set; }
    }
}
