//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int ID { get; set; }
        public Nullable<int> BillType { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> SettlementType { get; set; }
        public Nullable<System.DateTime> SettlementTime { get; set; }
        public Nullable<int> ChargeCurrency { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<decimal> ActualDiscount { get; set; }
        public Nullable<int> SettlementProperty { get; set; }
        public Nullable<System.DateTime> OccTime { get; set; }
        public Nullable<int> SettlementState { get; set; }
    }
}
