//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Scale { get; set; }
        public Nullable<int> Nature { get; set; }
        public Nullable<System.DateTime> FoundingTime { get; set; }
        public string Industry { get; set; }
        public string ChildIndustry { get; set; }
        public string RegisteredCapital { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public Nullable<System.DateTime> JoinTime { get; set; }
        public string ContactNum { get; set; }
        public string ExtendInfoPath { get; set; }
        public string LogoPath { get; set; }
        public string Email { get; set; }
    }
}
