//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> DrivingAge { get; set; }
        public Nullable<int> DrivingLicenseTypeID { get; set; }
        public string DriverPhotoPath { get; set; }
        public string EnableBusinessClass { get; set; }
        public Nullable<int> IsExistDrunkDrivingRecord { get; set; }
        public Nullable<int> WPDriverBelong { get; set; }
        public Nullable<int> WPGovLeaseID { get; set; }
        public Nullable<System.DateTime> WPDriverDate { get; set; }
    }
}
