//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseBillCheck
    {
        public int ID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> ApprovalState { get; set; }
        public Nullable<int> IsConfirmCharge { get; set; }
        public Nullable<System.DateTime> LastApprovalConfirmTime { get; set; }
        public Nullable<int> LastApprovalPersonID { get; set; }
        public string ApprovalPersonList { get; set; }
    }
}
