//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EStaffOrderRule
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string OrderBusinessClassList { get; set; }
        public string OrderVehicleLevelList { get; set; }
        public Nullable<int> IsDirToLeasingCompany { get; set; }
        public string OrderTime { get; set; }
        public string SettlementTypeList { get; set; }
        public Nullable<int> CustomCycleLengthMax { get; set; }
        public Nullable<int> IsNeedApproval { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
