//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public long ID { get; set; }
        public int InfoType { get; set; }
        public int InfoSenderID { get; set; }
        public int SenderType { get; set; }
        public int InfoRecverID { get; set; }
        public int RecverType { get; set; }
        public string InfoOperation { get; set; }
        public string InfoDesc { get; set; }
        public System.DateTime OccTime { get; set; }
        public Nullable<int> SenderDelFlag { get; set; }
        public Nullable<int> RecverDelFlag { get; set; }
    }
}
