//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCValuation
    {
        public int ID { get; set; }
        public Nullable<int> LeasingCompanyID { get; set; }
        public Nullable<int> ValuationCurrency { get; set; }
        public Nullable<int> FavorableCurrency { get; set; }
        public string ValuationFormula { get; set; }
        public double BaseValuation { get; set; }
        public string VehicleLevelValuation { get; set; }
        public string VehicleTypeValuation { get; set; }
        public string VehicleSLifeValuation { get; set; }
        public string UVTimeValuation { get; set; }
        public string UVDayValuation { get; set; }
        public string UVBCValuation { get; set; }
        public Nullable<System.DateTime> ActivityStartTime { get; set; }
        public Nullable<System.DateTime> ActivityEndTime { get; set; }
        public string ConsumeReductionRule { get; set; }
        public string ActivityUVLevelFavorable { get; set; }
        public string ActivityUVTypeFavorable { get; set; }
        public string ActivityUVTimeFavorable { get; set; }
        public string ActivityUVDayFavorable { get; set; }
        public string UVBCFavorable { get; set; }
    }
}
