//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeasingCompany
    {
        public int LeasingCompanyID { get; set; }
        public int CompanyInfoID { get; set; }
        public Nullable<int> VehicleNum { get; set; }
        public Nullable<int> AvableVehicleNum { get; set; }
        public Nullable<int> DriverNum { get; set; }
        public Nullable<int> AvableDriverNum { get; set; }
        public Nullable<int> GroupID { get; set; }
    }
}
