//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LongRentVehicleInfo
    {
        public int ID { get; set; }
        public Nullable<int> LeasingCompanyID { get; set; }
        public Nullable<int> PLeasingCompanyID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> PEnterpriseID { get; set; }
        public string LicenseNum { get; set; }
        public string Brand { get; set; }
        public Nullable<int> VehicleBelong { get; set; }
    }
}
