//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPRelationship
    {
        public int ID { get; set; }
        public Nullable<int> CooperateRegID { get; set; }
        public Nullable<int> LeasingCompanyID { get; set; }
        public Nullable<int> PartnerLeasingCompanyID { get; set; }
        public Nullable<int> ApplicationPartyLCID { get; set; }
        public Nullable<int> ConfigInfoID { get; set; }
    }
}
