//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfflineBillCharge
    {
        public int ID { get; set; }
        public int PayPartyID { get; set; }
        public int ChargePartyType { get; set; }
        public Nullable<int> ChargePartyID { get; set; }
        public int BillType { get; set; }
        public int Type { get; set; }
        public int Currency { get; set; }
        public string AmountDue { get; set; }
        public string ActualCost { get; set; }
        public string ActualDiscount { get; set; }
        public string Description { get; set; }
        public System.DateTime PayChargeTime { get; set; }
        public System.DateTime InDBTime { get; set; }
    }
}
