//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderVehicleTravel
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime OccTime { get; set; }
        public Nullable<decimal> TollCharge { get; set; }
        public Nullable<decimal> OilCharge { get; set; }
        public Nullable<decimal> ParkingCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public string OtherChargeDescription { get; set; }
        public string OilMass { get; set; }
        public string Oil { get; set; }
        public string ParkingCategory { get; set; }
        public string TollCategory { get; set; }
        public string WaitingTime { get; set; }
        public Nullable<int> TicketCount { get; set; }
        public string StoppingPlace { get; set; }
        public string WayPlace { get; set; }
        public string Overtime { get; set; }
    }
}
