//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int OrderID { get; set; }
        public int UseCarInfoID { get; set; }
        public string Applicant { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> CustomCycleLength { get; set; }
        public Nullable<System.DateTime> OccTime { get; set; }
        public Nullable<int> IsValid { get; set; }
        public Nullable<int> VDRID { get; set; }
        public Nullable<int> OrderState { get; set; }
        public Nullable<int> OrderMode { get; set; }
        public Nullable<System.DateTime> StateUpdateTime { get; set; }
        public Nullable<int> EContactStatue { get; set; }
        public Nullable<int> LContactStatue { get; set; }
        public Nullable<int> LVehicleOrigin { get; set; }
        public Nullable<int> EVehicleOrigin { get; set; }
        public Nullable<int> ActuallyVehicleID { get; set; }
        public Nullable<int> ActuallyDriverID { get; set; }
        public Nullable<int> OrderProperty { get; set; }
        public string ActualStartSite { get; set; }
        public Nullable<decimal> ActualStartSitelongitude { get; set; }
        public Nullable<decimal> ActualStartSitelatitude { get; set; }
        public string ActualEndSite { get; set; }
        public Nullable<decimal> ActualEndSitelongitude { get; set; }
        public Nullable<decimal> ActualEndSitelatitude { get; set; }
        public Nullable<decimal> StartKm { get; set; }
        public Nullable<decimal> EndKm { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<int> BillID { get; set; }
        public int CheckStatue { get; set; }
        public Nullable<int> BillCheckStatue { get; set; }
        public Nullable<int> OrderCompanyID { get; set; }
        public Nullable<int> SupplierID { get; set; }
    }
}
