//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseCarInfo2
    {
        public int ID { get; set; }
        public Nullable<int> UseVehicleMode { get; set; }
        public string Origin { get; set; }
        public string OriginLongitude { get; set; }
        public string OriginLatitude { get; set; }
        public string Destination { get; set; }
        public string DestinationLongitude { get; set; }
        public string DestinationLatitude { get; set; }
        public Nullable<System.DateTime> DepartTime { get; set; }
        public Nullable<System.DateTime> UseVehicleDate { get; set; }
        public Nullable<int> UseVehicleType { get; set; }
        public Nullable<int> UseVehicleLevel { get; set; }
        public Nullable<int> UseVehicleSeatingCapacity { get; set; }
        public Nullable<int> SettlementType { get; set; }
        public Nullable<int> CustomCycleLength { get; set; }
        public Nullable<int> PersonNum { get; set; }
        public string Remark { get; set; }
        public string Intend { get; set; }
        public string Dartment { get; set; }
        public string Passenger { get; set; }
        public string Journey { get; set; }
        public string CarUseCompany { get; set; }
        public Nullable<int> PayModel { get; set; }
        public Nullable<int> VehicleOrigin { get; set; }
        public string TaskDesc { get; set; }
        public Nullable<decimal> StrikePrice { get; set; }
        public Nullable<decimal> OrderOffer { get; set; }
        public Nullable<decimal> CollectFees { get; set; }
        public Nullable<System.DateTime> PreEndTime { get; set; }
    }
}
