//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> UserBaseID { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public Nullable<int> StaffWorkInfoID { get; set; }
        public string UserPhotoPath { get; set; }
    }
}
