//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuationRulesInfo
    {
        public int ValuationRulesID { get; set; }
        public Nullable<int> BelongsLeaseID { get; set; }
        public string ValuationRulesName { get; set; }
        public string ValuationObject { get; set; }
        public string ValuationTime { get; set; }
        public string ServerDays { get; set; }
        public Nullable<int> ServerTime { get; set; }
        public Nullable<decimal> ServerMileage { get; set; }
        public Nullable<decimal> ExcessiveOvertimeUnitPrice { get; set; }
        public Nullable<int> OverMileageCalculateWay { get; set; }
        public Nullable<decimal> SuperMileageUnitPrice { get; set; }
        public Nullable<int> RoadTollCalculateWay { get; set; }
        public string CustomersUsers { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> BaseRent { get; set; }
        public Nullable<int> ParkingFeeCalculateWay { get; set; }
    }
}
