//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBrandValuation
    {
        public int ID { get; set; }
        public Nullable<int> VehicleBelong { get; set; }
        public Nullable<int> GovLeaseID { get; set; }
        public string VehicleBrand { get; set; }
        public Nullable<double> Valuation { get; set; }
        public Nullable<double> ActivityFavorable { get; set; }
    }
}
