//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDriverWorking
    {
        public int ID { get; set; }
        public int UnitID { get; set; }
        public int VehicleDriverType { get; set; }
        public int Type { get; set; }
        public Nullable<int> TypeBelongsID { get; set; }
        public int ServingTime { get; set; }
        public Nullable<int> ServingDay { get; set; }
        public Nullable<int> WorkStatus { get; set; }
        public string Description { get; set; }
    }
}
