//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public string LicenseNum { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public string Brand { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleSource { get; set; }
        public string Color { get; set; }
        public Nullable<int> VehicleBelong { get; set; }
        public Nullable<int> GovLeaseID { get; set; }
        public Nullable<System.DateTime> VehicleDate { get; set; }
        public Nullable<int> WPVehicleBelong { get; set; }
        public Nullable<int> WPGovLeaseID { get; set; }
        public Nullable<System.DateTime> WPVehicleDate { get; set; }
        public Nullable<int> SeatingCapacity { get; set; }
        public string FuelType { get; set; }
        public string FuelCost { get; set; }
        public string GasDisplacement { get; set; }
        public Nullable<int> ServicedLife { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> RemainValue { get; set; }
        public string VehiclePhotoPath { get; set; }
        public string EnableBusinessClassList { get; set; }
        public Nullable<int> VehicleProperty { get; set; }
    }
}
