//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class 学生表
    {
        public int 学号 { get; set; }
        public string 姓名 { get; set; }
        public string 性别 { get; set; }
        public Nullable<System.DateTime> 出生日期 { get; set; }
        public byte 院系编号 { get; set; }
        public byte 专业编号 { get; set; }
        public string 出生地 { get; set; }
        public string 政治面貌 { get; set; }
        public string 备注 { get; set; }
    }
}
