//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class 成绩表
    {
        public int 学号 { get; set; }
        public int 教师编号 { get; set; }
        public byte 课程号 { get; set; }
        public Nullable<decimal> 分数 { get; set; }
    }
}
