//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class 教师表
    {
        public int 教师编号 { get; set; }
        public string 姓名 { get; set; }
        public System.DateTime 出生日期 { get; set; }
        public string 性别 { get; set; }
        public Nullable<byte> 院系编号 { get; set; }
        public string 学历 { get; set; }
        public string 备注 { get; set; }
    }
}
